def read_csv_py(file_path: str) -> tuple[list[float], list[float]]: ...
def compute_fft_py(data: list[float]) -> tuple[list[float], list[float]]: ...
def fft_shift_py(real: list[float], imag: list[float]) -> tuple[list[float], list[float]]: ...
def compute_magnitude_py(real: list[float], imag: list[float]) -> list[float]: ...
def generate_frequencies_py(len: int, sampling_interval: float) -> list[float]: ...
def fft_shift_frequencies_py(data: list[float]) -> list[float]: ...
def generate_plot_py(
    x: list[float],
    y: list[float],
    x_label: str,
    y_label: str,
    title: str,
) -> bytes: ...
